version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "springtest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4rxsoscio2w0"
s3_prefix = "springtest"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
